settings:
  readme_file: "./TEMPLATE.md"
  disabled_events:
    - "comments"
  date:
    timezone: "Asia/Kolkata"
    text: '<p align="center">Last refresh: <b>{DATE} IST</b>'
    max_lines: 10
messages:
  comments: "![comment] Commented on {ID} in {REPO}"
  issue_opened: "![issueOpened] Opened issue {ID} in {REPO}"
  issue_closed: "![issueClosed] Closed issue {ID} in {REPO}"
  pr_opened: "![pullrequestopened] Opened PR {ID} in {REPO}"
  pr_closed: "![pullrequestclosed] Closed PR {ID} in {REPO}"
  pr_merged: "![pullrequestmerged] Merged PR {ID} in {REPO}"
  create_repo: "![repoCreated] Created new repository {REPO}"
  new_star: "![star] Starred {REPO}"
  fork_repo: "![fork] Forked {FORK} from {REPO}"
  wiki_create: "![wiki] Created new wiki page {WIKI} in {REPO}"
  changes_approved: "![approved] Approved {ID} in {REPO}"
  changes_requested: "![changesRequested] Requested changes in {ID} in {REPO}"
  new_release: "![release] Released {ID} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
