name: Test Replacer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/readme-replacer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_EMAIL: "abhijoshi2k@gmail.com"
          COMMIT_NAME: "Abhishek Joshi"
          COMMIT_FILE: "./TEMPLATE.md"
          TIMEZONE: "Asia/Kolkata"

      - uses: actions-js/profile-readme@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: abhijoshi2k
          template: "TEMPLATE.md"

      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
