name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@github-secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_A: ${{ secrets.TEST_SECRET }}
        with:
          CONFIG_FILE: "./.github/update-readme.config.yml"
          TEST: ${{ secrets.TEST_SECRET }}

      - uses: actions-js/profile-readme@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: abhijoshi2k
          template: "TEMPLATE.md"

      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
