name: Update README

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@issue#5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          README_FILE: ./TEMPLATE.md
          COMMENTS_ACTIVITY: 'test {ID} in {REPO}'
