name: Update README

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@add-events
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          README_FILE: ./TEMPLATE.md
          DISABLE_EVENTS: "comments"
          COMMENTS_ACTIVITY: "![comment] Commented on {ID} in {REPO}"
          ISSUE_OPENED: "![issueOpened] Opened issue {ID} in {REPO}"
          ISSUE_CLOSED: "![issueClosed] Closed issue {ID} in {REPO}"
          PR_OPENED: "![pullRequestOpened] Opened PR {ID} in {REPO}"
          PR_CLOSED: "![pullRequestClosed] Closed PR {ID} in {REPO}"
          PR_MERGED: "![pullRequestMerged] Merged PR {ID} in {REPO}"
          TIMEZONE_OFFSET: "GMT+5:30"
          DATE_STRING: '<p align="center">Last refresh: <b>{DATE} IST</b>'
          MAX_LINES: 10

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate README.md
        uses: actions-js/profile-readme@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: abhijoshi2k
          template: "TEMPLATE.md"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
