name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@timezone-fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          README_FILE: ./TEMPLATE.md
          DISABLE_EVENTS: "comments"
          COMMENTS_ACTIVITY: "![comment] Commented on {ID} in {REPO}"
          ISSUE_OPENED: "![issueOpened] Opened issue {ID} in {REPO}"
          ISSUE_CLOSED: "![issueClosed] Closed issue {ID} in {REPO}"
          PR_OPENED: "![pullRequestOpened] Opened PR {ID} in {REPO}"
          PR_CLOSED: "![pullRequestClosed] Closed PR {ID} in {REPO}"
          PR_MERGED: "![pullRequestMerged] Merged PR {ID} in {REPO}"
          TIMEZONE: "Asia/Kolkata"
          DATE_STRING: '<p align="center">Last refresh: <b>{DATE} IST</b>'
          MAX_LINES: 10

      - uses: actions-js/profile-readme@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: abhijoshi2k
          template: "TEMPLATE.md"

      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
